#!/usr/bin/env python3

import html
import json
import os
import re
import shutil
import subprocess
from pathlib import Path

# ============================================================
# Configuration
# ============================================================

ROOT = Path.cwd()
SITE = ROOT / "_site"

REPO = os.environ.get("GITHUB_REPOSITORY", "")
REPO_NAME = REPO.split("/", 1)[1] if "/" in REPO else ROOT.name

TEMP_DIR = Path(os.environ.get("RUNNER_TEMP", "/tmp"))
MERGED_PRS_FILE = TEMP_DIR / "merged-prs.json"

# Bootstrap is downloaded by pages.yml into this directory.
BOOTSTRAP_DIR = SITE / "assets"
BOOTSTRAP_CSS = BOOTSTRAP_DIR / "bootstrap.min.css"
BOOTSTRAP_JS = BOOTSTRAP_DIR / "bootstrap.bundle.min.js"

# Files which should never be rendered as source files.
EXCLUDED_FILES = {
  ".git",
  ".github",
  "_site",
  "merged-prs.json",
  ".DS_Store",
}

# File extensions which are useful to display.
SOURCE_EXTENSIONS = {
  ".java",
  ".xml",
  ".yml",
  ".yaml",
  ".properties",
  ".md",
  ".txt",
  ".json",
  ".gradle",
  ".kts",
}

# Search is deliberately restricted to Java files.
SEARCH_EXTENSIONS = {".java"}

CONTEXT_LINES = 2
MAX_MATCH_LINES_PER_FILE = 10


# ============================================================
# Utility functions
# ============================================================

def run(command, cwd=None):
  """Run a command and return stdout."""
  result = subprocess.run(
    command,
    cwd=cwd,
    check=True,
    text=True,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
  )
  return result.stdout.strip()


def git(command):
  """Run a git command in the repository."""
  return run(["git"] + command, cwd=ROOT)


def safe_text(value):
  if value is None:
    return ""
  return str(value)


def html_escape(value):
  return html.escape(safe_text(value), quote=True)


def normalize_path(path):
  return str(path).replace("\\", "/")


def is_excluded(path):
  """
  Return True if a repository path contains a directory/file
  which should not be published.
  """
  parts = Path(path).parts

  for part in parts:
    if part in EXCLUDED_FILES:
      return True

  return False


def is_source_file(path):
  if is_excluded(path):
    return False

  return Path(path).suffix.lower() in SOURCE_EXTENSIONS


def is_searchable_file(path):
  if is_excluded(path):
    return False

  return Path(path).suffix.lower() in SEARCH_EXTENSIONS


def read_text_file(path):
  try:
    return path.read_text(encoding="utf-8")
  except UnicodeDecodeError:
    return path.read_text(encoding="utf-8", errors="replace")


def write_text(path, content):
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text(content, encoding="utf-8")


def clean_site():
  if SITE.exists():
    shutil.rmtree(SITE)

  SITE.mkdir(parents=True)


# ============================================================
# Git / PR information
# ============================================================

def load_merged_prs():
  """
  Read merged PR metadata generated by pages.yml.

  Expected JSON:
  [
    {
      "number": 12,
      "title": "...",
      "mergeCommit": {
        "oid": "..."
      },
      "mergedAt": "..."
    }
  ]
  """

  if not MERGED_PRS_FILE.exists():
    print("No merged-prs.json found.")
    return []

  try:
    data = json.loads(read_text_file(MERGED_PRS_FILE))
  except json.JSONDecodeError as exc:
    print(f"WARNING: Could not parse {MERGED_PRS_FILE}: {exc}")
    return []

  if not isinstance(data, list):
    return []

  result = []

  for pr in data:
    if not isinstance(pr, dict):
      continue

    number = pr.get("number")
    title = pr.get("title") or f"Pull Request #{number}"

    merge_commit = pr.get("mergeCommit") or {}
    sha = merge_commit.get("oid")

    merged_at = pr.get("mergedAt") or ""

    if not number or not sha:
      continue

    result.append(
      {
        "number": int(number),
        "title": title,
        "sha": sha,
        "mergedAt": merged_at,
      }
    )

  # Newest merged PR first.
  result.sort(
    key=lambda item: item.get("mergedAt", ""),
    reverse=True,
  )

  return result


def get_main_commit():
  return git(["rev-parse", "HEAD"])


# ============================================================
# Source snapshot handling
# ============================================================

def create_snapshot_from_commit(commit, destination):
  """
  Create a complete repository snapshot for a git commit.

  git archive is used instead of checking out the commit, so the
  generator itself can continue running from the current checkout.
  """

  if destination.exists():
    shutil.rmtree(destination)

  destination.mkdir(parents=True)

  archive = subprocess.Popen(
    ["git", "archive", commit],
    cwd=ROOT,
    stdout=subprocess.PIPE,
  )

  try:
    subprocess.run(
      ["tar", "-x", "-C", str(destination)],
      stdin=archive.stdout,
      check=True,
    )
  finally:
    if archive.stdout:
      archive.stdout.close()

  return destination


# ============================================================
# Bootstrap
# ============================================================

def copy_bootstrap():
  """
  Bootstrap is downloaded by pages.yml.

  Keeping it locally in the generated Pages site means learners
  do not need access to jsdelivr.net or another external CDN.
  """

  if not BOOTSTRAP_CSS.exists():
    raise RuntimeError(
      f"Bootstrap CSS not found: {BOOTSTRAP_CSS}"
    )

  if not BOOTSTRAP_JS.exists():
    raise RuntimeError(
      f"Bootstrap JS not found: {BOOTSTRAP_JS}"
    )


# ============================================================
# URL handling
# ============================================================

def site_base():
  """
  GitHub Pages project sites are normally published below:

      /repository-name/

  This is important because the generated site is not necessarily
  hosted at the domain root.
  """

  return "/" + REPO_NAME.strip("/") + "/"


def version_base(version_type, pr_number=None):
  base = site_base()

  if version_type == "main":
    return base

  if version_type == "pr":
    return base + f"pr/{pr_number}/"

  raise ValueError(f"Unknown version type: {version_type}")


def relative_url_from_version(version_base_url, path):
  return version_base_url + normalize_path(path)


# ============================================================
# Syntax highlighting
# ============================================================

def get_lexer_for_file(path):
  try:
    from pygments.lexers import (
      JavaLexer,
      XmlLexer,
      YamlLexer,
      JsonLexer,
      PropertiesLexer,
      MarkdownLexer,
      TextLexer,
    )
  except ImportError:
    return None

  suffix = Path(path).suffix.lower()

  if suffix == ".java":
    return JavaLexer()

  if suffix == ".xml":
    return XmlLexer()

  if suffix in {".yml", ".yaml"}:
    return YamlLexer()

  if suffix == ".json":
    return JsonLexer()

  if suffix == ".properties":
    return PropertiesLexer()

  if suffix == ".md":
    return MarkdownLexer()

  return TextLexer()


def highlight_source(path, content):
  """
  Highlight source using Pygments.

  If Pygments cannot identify a lexer, plain escaped text is used.
  """

  try:
    from pygments import highlight
    from pygments.formatters import HtmlFormatter
  except ImportError:
    return html_escape(content)

  lexer = get_lexer_for_file(path)

  if lexer is None:
    return html_escape(content)

  formatter = HtmlFormatter(nowrap=True)

  highlighted = highlight(
    content,
    lexer,
    formatter,
  )

  return highlighted


# ============================================================
# Markdown
# ============================================================

def render_markdown(content):
  try:
    import markdown

    return markdown.markdown(
      content,
      extensions=[
        "fenced_code",
        "tables",
        "toc",
      ],
    )

  except ImportError:
    return (
      "<pre class=\"p-3 bg-body-tertiary rounded\">"
      + html_escape(content)
      + "</pre>"
    )


# ============================================================
# Directory tree
# ============================================================

def build_tree(root):
  """
  Return a nested dictionary representing the source tree.

  Directories:
      {
        "src": {
           "main": {
              "java": {
                  "__files__": [...]
              }
           }
        }
      }
  """

  tree = {}

  for path in sorted(root.rglob("*")):
    if not path.is_file():
      continue

    relative = path.relative_to(root)
    relative_string = normalize_path(relative)

    if is_excluded(relative_string):
      continue

    if not is_source_file(relative_string):
      continue

    parts = list(relative.parts)

    current = tree

    for directory in parts[:-1]:
      current = current.setdefault(directory, {})

    current.setdefault("__files__", []).append(parts[-1])

  return tree


def tree_has_content(node):
  for key, value in node.items():
    if key == "__files__":
      if value:
        return True
    elif isinstance(value, dict) and tree_has_content(value):
      return True

  return False


def render_tree_node(
  node,
  version_base_url,
  parent_id="tree-root",
  level=0,
):
  """
  Render a Bootstrap collapsible directory tree.

  The generated HTML intentionally uses normal strings instead
  of Python f-strings.
  """

  pieces = []

  directories = sorted(
    key for key in node.keys()
    if key != "__files__"
  )

  files = sorted(node.get("__files__", []))

  for directory in directories:
    child = node[directory]

    if not tree_has_content(child):
      continue

    safe_id = re.sub(
      r"[^A-Za-z0-9_-]",
      "-",
      parent_id + "-" + directory,
    )

    child_html = render_tree_node(
      child,
      version_base_url,
      parent_id=safe_id,
      level=level + 1,
    )

    pieces.append(
      '<div class="tree-directory mb-1">'
      '<button '
      'class="btn btn-sm btn-toggle w-100 text-start" '
      'type="button" '
      'data-bs-toggle="collapse" '
      'data-bs-target="#'
      + html_escape(safe_id)
      + '" '
        'aria-expanded="'
      + ("true" if level == 0 else "false")
      + '">'
        '<span class="tree-icon">▸</span> '
      + html_escape(directory)
      + '</button>'
        '<div id="'
      + html_escape(safe_id)
      + '" class="collapse '
      + ("show" if level == 0 else "")
      + '">'
        '<div class="ms-3 ps-2 border-start">'
      + child_html
      + "</div>"
        "</div>"
        "</div>"
    )

  for filename in files:
    relative_path = find_relative_file_path(
      node,
      filename,
      prefix=[],
    )

    # The helper above cannot determine the full path from this
    # local node alone. File links are therefore rebuilt by the
    # recursive tree renderer below.
    #
    # This branch is intentionally replaced by the simpler
    # render_tree_node_with_prefix implementation.
    _ = relative_path

  return "".join(pieces)


def render_tree_node_with_prefix(
  node,
  version_base_url,
  prefix=None,
  parent_id="tree-root",
  level=0,
):
  """
  Recursive tree renderer which knows the complete file path.
  """

  if prefix is None:
    prefix = []

  pieces = []

  directories = sorted(
    key for key in node.keys()
    if key != "__files__"
  )

  files = sorted(node.get("__files__", []))

  for directory in directories:
    child = node[directory]

    if not tree_has_content(child):
      continue

    safe_id = re.sub(
      r"[^A-Za-z0-9_-]",
      "-",
      parent_id + "-" + directory,
    )

    child_html = render_tree_node_with_prefix(
      child,
      version_base_url,
      prefix=prefix + [directory],
      parent_id=safe_id,
      level=level + 1,
    )

    pieces.append(
      '<div class="tree-directory mb-1">'
      '<button '
      'class="btn btn-sm btn-toggle w-100 text-start" '
      'type="button" '
      'data-bs-toggle="collapse" '
      'data-bs-target="#'
      + html_escape(safe_id)
      + '" '
        'aria-expanded="'
      + ("true" if level == 0 else "false")
      + '">'
        '<span class="tree-icon">▸</span> '
      + html_escape(directory)
      + '</button>'
        '<div id="'
      + html_escape(safe_id)
      + '" class="collapse '
      + ("show" if level == 0 else "")
      + '">'
        '<div class="ms-3 ps-2 border-start">'
      + child_html
      + "</div>"
        "</div>"
        "</div>"
    )

  for filename in files:
    relative_path = "/".join(prefix + [filename])

    url = relative_url_from_version(
      version_base_url,
      relative_path.replace(
        Path(filename).suffix,
        ".html",
      ),
    )

    pieces.append(
      '<a class="tree-file d-block text-decoration-none '
      'small py-1 px-2 rounded" href="'
      + html_escape(url)
      + '">'
        '<span class="text-body-secondary me-1">•</span>'
      + html_escape(filename)
      + "</a>"
    )

  return "".join(pieces)


def find_relative_file_path(node, filename, prefix):
  """
  Retained for compatibility with the simpler renderer.
  """

  files = node.get("__files__", [])

  if filename in files:
    return "/".join(prefix + [filename])

  for directory, child in node.items():
    if directory == "__files__":
      continue

    result = find_relative_file_path(
      child,
      filename,
      prefix + [directory],
    )

    if result:
      return result

  return None


# ============================================================
# Source file rendering
# ============================================================

def render_source_file(
  source_root,
  relative_path,
  version_base_url,
):
  source_path = source_root / relative_path

  content = read_text_file(source_path)

  highlighted = highlight_source(
    relative_path,
    content,
  )

  escaped_title = html_escape(relative_path)

  page_title = (
    html_escape(Path(relative_path).name)
    + " – "
    + html_escape(REPO_NAME)
  )

  selector = build_version_selector(
    version_base_url,
  )

  tree = build_tree(source_root)

  sidebar = render_tree_node_with_prefix(
    tree,
    version_base_url,
  )

  body = (
    '<div class="container-fluid py-4">'
    '<div class="row g-4">'

    '<aside class="col-lg-3 col-xl-2">'
    + render_sidebar(
    selector,
    sidebar,
    version_base_url,
  )
    + "</aside>"

      '<main class="col-lg-9 col-xl-10">'

      '<div class="d-flex flex-wrap justify-content-between '
      'align-items-center gap-2 mb-3">'
      '<div>'
      '<div class="text-body-secondary small">'
      'Quelldatei'
      "</div>"
      '<h1 class="h4 mb-0">'
    + escaped_title
    + "</h1>"
      "</div>"
      '<a class="btn btn-outline-secondary btn-sm" href="'
    + html_escape(version_base_url + "index.html")
    + '">Projektübersicht</a>'
      "</div>"

      '<div class="source-wrapper">'
      '<table class="source-table">'
      '<tbody>'
    + render_numbered_source(
    highlighted,
  )
    + "</tbody>"
      "</table>"
      "</div>"

      "</main>"
      "</div>"
      "</div>"
  )

  return render_page(
    title=page_title,
    body=body,
    version_base_url=version_base_url,
  )


def render_numbered_source(highlighted):
  """
  Pygments produces one HTML fragment per source line.

  We wrap each line in a table row with a line-number anchor.
  """

  lines = highlighted.splitlines()

  rows = []

  for number, line in enumerate(lines, start=1):
    if not line:
      line = " "

    rows.append(
      '<tr id="line-'
      + str(number)
      + '">'
        '<td class="line-number">'
        '<a href="#line-'
      + str(number)
      + '">'
      + str(number)
      + "</a>"
        "</td>"
        '<td class="source-line"><code>'
      + line
      + "</code></td>"
        "</tr>"
    )

  if not rows:
    rows.append(
      '<tr>'
      '<td class="line-number">1</td>'
      '<td class="source-line"><code></code></td>'
      "</tr>"
    )

  return "".join(rows)


# ============================================================
# Search index
# ============================================================

def create_search_index(source_root):
  """
  Create a compact search index containing all Java files.

  The complete Java content is included because this allows
  client-side searching on GitHub Pages without a server.
  """

  files = []

  for path in sorted(source_root.rglob("*.java")):
    relative = path.relative_to(source_root)
    relative_string = normalize_path(relative)

    if is_excluded(relative_string):
      continue

    content = read_text_file(path)

    html_path = (
      str(Path(relative_string).with_suffix(".html"))
      .replace("\\", "/")
    )

    files.append(
      {
        "name": path.name,
        "path": relative_string,
        "url": html_path,
        "content": content,
      }
    )

  return files


def write_search_index(
  source_root,
  version_directory,
):
  index = create_search_index(source_root)

  path = version_directory / "search-index.js"

  content = (
    "window.SEARCH_INDEX = "
    + json.dumps(
    index,
    ensure_ascii=False,
    separators=(",", ":"),
  )
    + ";"
  )

  write_text(path, content)


# ============================================================
# Search UI
# ============================================================

def render_search_box(version_base_url):
  return (
    '<div class="card shadow-sm mb-3">'
    '<div class="card-body">'
    '<label for="searchInput" class="form-label fw-semibold">'
    'Java-Code durchsuchen'
    "</label>"

    '<div class="input-group">'
    '<input '
    'id="searchInput" '
    'type="search" '
    'class="form-control" '
    'placeholder="z. B. public class, System.out, main ..." '
    'autocomplete="off">'
    '<button id="clearSearch" class="btn btn-outline-secondary" '
    'type="button">Löschen</button>'
    "</div>"

    '<div class="form-text">'
    'Die Suche erfolgt ausschließlich in den Java-Dateien dieser Version.'
    "</div>"

    '<div id="searchStatus" class="small text-body-secondary mt-2">'
    "</div>"

    '<div id="searchResults" class="mt-3"></div>'

    "</div>"
    "</div>"
  )


# ============================================================
# Version selector
# ============================================================

def load_versions():
  versions = [
    {
      "type": "main",
      "label": "main – aktuell",
      "url": site_base() + "index.html",
    }
  ]

  for pr in load_merged_prs():
    versions.append(
      {
        "type": "pr",
        "number": pr["number"],
        "label": (
          f"PR #{pr['number']} – "
          f"{pr['title']}"
        ),
        "mergedAt": pr["mergedAt"],
        "url": (
          site_base()
          + f"pr/{pr['number']}/index.html"
        ),
      }
    )

  return versions


def build_version_selector(version_base_url):
  versions = load_versions()

  current_url = version_base_url + "index.html"

  options = []

  for version in versions:
    selected = (
      " selected"
      if version["url"] == current_url
      else ""
    )

    label = version["label"]

    if version["type"] == "pr" and version.get("mergedAt"):
      label += " (" + version["mergedAt"][:10] + ")"

    options.append(
      '<option value="'
      + html_escape(version["url"])
      + '"'
      + selected
      + ">"
      + html_escape(label)
      + "</option>"
    )

  return (
    '<label for="versionSelector" '
    'class="form-label fw-semibold">'
    "Version"
    "</label>"
    '<select id="versionSelector" class="form-select">'
    + "".join(options)
    + "</select>"
  )


# ============================================================
# Sidebar
# ============================================================

def render_sidebar(
  selector,
  tree,
  version_base_url,
):
  parts = [
    '<div class="sticky-lg-top sidebar-top">',
    selector,
    render_search_box(version_base_url),
    '<div class="card shadow-sm">',
    '<div class="card-header fw-semibold">',
    'Projektstruktur',
    '</div>',
    '<div class="card-body p-2">',
    tree,
    '</div>',
    '</div>',
    '</div>',
  ]

  return "".join(parts)


# ============================================================
# Project overview
# ============================================================

def render_readme(source_root):
  readme = source_root / "README.md"

  if not readme.exists():
    return ""

  content = read_text_file(readme)

  return (
    '<section class="mb-4">'
    '<h2 class="h4">README</h2>'
    '<div class="card shadow-sm">'
    '<div class="card-body markdown-body">'
    + render_markdown(content)
    + "</div>"
      "</div>"
      "</section>"
  )


def render_pom(source_root, version_base_url):
  pom = source_root / "pom.xml"

  if not pom.exists():
    return ""

  content = read_text_file(pom)

  return (
    '<section class="mb-4">'
    '<h2 class="h4">pom.xml</h2>'
    '<p class="text-body-secondary">'
    'Maven-Projektkonfiguration'
    "</p>"
    '<a class="btn btn-outline-primary btn-sm" href="'
    + html_escape(
    version_base_url + "pom.html"
  )
    + '">'
      "pom.xml anzeigen"
      "</a>"
      "</section>"
  )


def render_project_overview(
  source_root,
  version_type,
  version_base_url,
  pr=None,
):
  if version_type == "main":
    title = "Maven-Projekt"
    subtitle = (
      'Aktueller Stand des Projekts aus dem Branch '
      '<code>main</code>.'
    )
  else:
    title = (
      "PR #"
      + str(pr["number"])
      + " – "
      + html_escape(pr["title"])
    )

    subtitle = (
      "Projektstand nach dem Merge dieses Pull Requests."
    )

  selector = build_version_selector(
    version_base_url,
  )

  tree = build_tree(source_root)

  sidebar_tree = render_tree_node_with_prefix(
    tree,
    version_base_url,
  )

  sidebar = render_sidebar(
    selector,
    sidebar_tree,
    version_base_url,
  )

  search = render_search_box(
    version_base_url,
  )

  readme = render_readme(source_root)

  pom = render_pom(
    source_root,
    version_base_url,
  )

  parts = [
    '<div class="container-fluid py-4">',
    '<div class="row g-4">',

    '<aside class="col-lg-3 col-xl-2">',
    sidebar,
    '</aside>',

    '<main class="col-lg-9 col-xl-10">',

    '<div class="d-flex flex-wrap '
    'justify-content-between '
    'align-items-start gap-3 mb-4">',

    '<div>',
    '<div class="text-body-secondary small">',
    'Java / Maven',
    '</div>',

    '<h1 class="display-6 fw-semibold">',
    title,
    '</h1>',

    '<p class="lead">',
    subtitle,
    '</p>',

    '</div>',

    '<button '
    'id="themeToggle" '
    'class="btn btn-outline-secondary">',
    '☾ Dark Mode',
    '</button>',

    '</div>',

    readme,
    pom,
    search,

    '</main>',
    '</div>',
    '</div>',
  ]

  body = "".join(parts)

  return render_page(
    title=title,
    body=body,
    version_base_url=version_base_url,
  )


# ============================================================
# Page template
# ============================================================

def render_page(
  title,
  body,
  version_base_url,
):
  """
  Complete HTML document.

  IMPORTANT:
  This is intentionally NOT an f-string.

  JavaScript/CSS braces therefore require no escaping.
  """

  template = r"""<!doctype html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>__TITLE__</title>

    <link
        rel="stylesheet"
        href="__SITE_BASE__assets/bootstrap.min.css">

    <style>
        :root {
            --source-bg: #f8f9fa;
            --source-border: #dee2e6;
            --line-number: #6c757d;
        }

        [data-bs-theme="dark"] {
            --source-bg: #15171a;
            --source-border: #343a40;
            --line-number: #8b949e;
        }

        body {
            min-height: 100vh;
        }

        .sidebar-top {
            top: 1rem;
        }

        .tree-file {
            color: var(--bs-body-color);
        }

        .tree-file:hover {
            background: var(--bs-tertiary-bg);
        }

        .btn-toggle {
            color: var(--bs-body-color);
        }

        .btn-toggle:hover {
            background: var(--bs-tertiary-bg);
        }

        .tree-icon {
            display: inline-block;
            width: 1.2rem;
            transition: transform 0.15s ease;
        }

        .btn-toggle[aria-expanded="true"] .tree-icon {
            transform: rotate(90deg);
        }

        .source-wrapper {
            overflow-x: auto;
            border: 1px solid var(--source-border);
            border-radius: 0.5rem;
            background: var(--source-bg);
        }

        .source-table {
            width: 100%;
            border-collapse: collapse;
            font-family:
                ui-monospace,
                SFMono-Regular,
                Menlo,
                Monaco,
                Consolas,
                "Liberation Mono",
                "Courier New",
                monospace;
            font-size: 0.9rem;
        }

        .source-table tr:target {
            background: rgba(255, 193, 7, 0.18);
        }

        .line-number {
            width: 1%;
            min-width: 4.5rem;
            padding: 0 0.75rem;
            text-align: right;
            vertical-align: top;
            user-select: none;
            color: var(--line-number);
            border-right: 1px solid var(--source-border);
        }

        .line-number a {
            color: inherit;
            text-decoration: none;
        }

        .source-line {
            padding: 0 1rem;
            white-space: pre;
        }

        .source-line code {
            color: var(--bs-body-color);
        }

        .search-result {
            border-left: 4px solid var(--bs-primary);
        }

        .search-context {
            overflow-x: auto;
            white-space: pre;
            font-family:
                ui-monospace,
                SFMono-Regular,
                Menlo,
                Monaco,
                Consolas,
                monospace;
            font-size: 0.82rem;
        }

        .search-context .match-line {
            background: rgba(255, 193, 7, 0.2);
            font-weight: 600;
        }

        .search-context .context-line {
            color: var(--bs-secondary-color);
        }

        .markdown-body pre {
            padding: 1rem;
            border-radius: 0.5rem;
            overflow-x: auto;
            background: var(--bs-tertiary-bg);
        }

        .markdown-body code {
            word-break: break-word;
        }

        .markdown-body img {
            max-width: 100%;
            height: auto;
        }

        @media (max-width: 991.98px) {
            .sidebar-top {
                position: static !important;
            }
        }
    </style>
</head>

<body>
    __BODY__

    <script src="__SITE_BASE__assets/bootstrap.bundle.min.js"></script>
    <script src="__SITE_BASE__site.js"></script>

    <script>
        window.VERSION_BASE = "__VERSION_BASE__";
    </script>
</body>
</html>
"""

  result = template
  result = result.replace(
    "__TITLE__",
    html_escape(title),
  )
  result = result.replace(
    "__BODY__",
    body,
  )
  result = result.replace(
    "__SITE_BASE__",
    site_base(),
  )
  result = result.replace(
    "__VERSION_BASE__",
    version_base_url,
  )

  return result


# ============================================================
# Global JavaScript
# ============================================================

def write_site_javascript():
  """
  Write the JavaScript needed by all generated pages.

  It is still generated from this Python file; there is no
  JavaScript source file in the repository.
  """

  js = r"""
(function () {
    "use strict";

    /*
     * Version selector
     */
    const versionSelector =
        document.getElementById("versionSelector");

    if (versionSelector) {
        versionSelector.addEventListener("change", function () {
            const target = this.value;

            if (target) {
                window.location.href = target;
            }
        });
    }


    /*
     * Dark mode
     */
    const themeToggle =
        document.getElementById("themeToggle");

    function getPreferredTheme() {
        const stored =
            localStorage.getItem("pages-theme");

        if (stored === "light" || stored === "dark") {
            return stored;
        }

        if (
            window.matchMedia &&
            window.matchMedia(
                "(prefers-color-scheme: dark)"
            ).matches
        ) {
            return "dark";
        }

        return "light";
    }

    function updateThemeButton(theme) {
        if (!themeToggle) {
            return;
        }

        if (theme === "dark") {
            themeToggle.textContent = "☀ Light Mode";
        } else {
            themeToggle.textContent = "☾ Dark Mode";
        }
    }

    function setTheme(theme) {
        document.documentElement.setAttribute(
            "data-bs-theme",
            theme
        );

        localStorage.setItem(
            "pages-theme",
            theme
        );

        updateThemeButton(theme);
    }

    const initialTheme =
        getPreferredTheme();

    setTheme(initialTheme);

    if (themeToggle) {
        themeToggle.addEventListener(
            "click",
            function () {
                const current =
                    document.documentElement.getAttribute(
                        "data-bs-theme"
                    );

                setTheme(
                    current === "dark"
                        ? "light"
                        : "dark"
                );
            }
        );
    }


    /*
     * Search
     *
     * Search index is loaded dynamically.
     */
    const searchInput =
        document.getElementById("searchInput");

    const searchResults =
        document.getElementById("searchResults");

    const searchStatus =
        document.getElementById("searchStatus");

    const clearSearch =
        document.getElementById("clearSearch");

    if (!searchInput || !searchResults) {
        return;
    }

    const script =
        document.createElement("script");

    script.src =
        (window.VERSION_BASE || "") +
        "search-index.js";

    script.onload = function () {
        window.SEARCH_INDEX =
            window.SEARCH_INDEX || [];

        searchInput.disabled = false;

        if (searchStatus) {
            searchStatus.textContent =
                window.SEARCH_INDEX.length +
                " Java-Dateien geladen.";
        }
    };

    script.onerror = function () {
        if (searchStatus) {
            searchStatus.textContent =
                "Suchindex konnte nicht geladen werden.";
        }
    };

    searchInput.disabled = true;

    document.body.appendChild(script);


    /*
     * Escape HTML for search results.
     */
    function escapeHtml(value) {
        return String(value)
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;")
            .replace(/'/g, "&#039;");
    }


    /*
     * Highlight search text.
     */
    function highlightText(text, query) {
        const escaped =
            escapeHtml(text);

        if (!query) {
            return escaped;
        }

        const escapedQuery =
            escapeHtml(query)
                .replace(
                    /[.*+?^${}()|[\]\\]/g,
                    "\\$&"
                );

        const regex =
            new RegExp(
                "(" + escapedQuery + ")",
                "gi"
            );

        return escaped.replace(
            regex,
            "<mark>$1</mark>"
        );
    }


    /*
     * Build one search result.
     */
    function buildResult(file, lineNumber, lines, query) {
        const start =
            Math.max(
                0,
                lineNumber - 1 - 2
            );

        const end =
            Math.min(
                lines.length,
                lineNumber + 2
            );

        let contextHtml = "";

        for (let i = start; i < end; i++) {
            const actualLine =
                i + 1;

            const className =
                actualLine === lineNumber
                    ? "match-line"
                    : "context-line";

            contextHtml +=
                '<div class="' +
                className +
                '">' +
                '<span class="text-body-secondary me-3">' +
                String(actualLine).padStart(5, " ") +
                "</span>" +
                highlightText(
                    lines[i],
                    query
                ) +
                "</div>";
        }

        const url =
            (window.VERSION_BASE || "") +
            file.url +
            "#line-" +
            lineNumber;

        return (
            '<div class="card search-result mb-3 shadow-sm">' +
                '<div class="card-body">' +

                    '<div class="d-flex justify-content-between ' +
                    'align-items-start gap-2 mb-2">' +

                        '<div>' +
                            '<a class="fw-semibold" href="' +
                            escapeHtml(url) +
                            '">' +
                            escapeHtml(file.path) +
                            "</a>" +
                        "</div>" +

                        '<span class="badge text-bg-secondary">' +
                            "Zeile " +
                            lineNumber +
                        "</span>" +

                    "</div>" +

                    '<div class="search-context">' +
                        contextHtml +
                    "</div>" +

                "</div>" +
            "</div>"
        );
    }


    /*
     * Perform search.
     */
    function performSearch() {
        const query =
            searchInput.value.trim();

        searchResults.innerHTML = "";

        if (!query) {
            if (searchStatus) {
                searchStatus.textContent =
                    window.SEARCH_INDEX
                        ? window.SEARCH_INDEX.length +
                          " Java-Dateien geladen."
                        : "";
            }

            return;
        }

        if (!window.SEARCH_INDEX) {
            if (searchStatus) {
                searchStatus.textContent =
                    "Suchindex wird noch geladen ...";
            }

            return;
        }

        const normalizedQuery =
            query.toLowerCase();

        let totalMatches = 0;
        let filesWithMatches = 0;

        const resultFragments = [];

        for (const file of window.SEARCH_INDEX) {
            const lines =
                String(file.content || "")
                    .split(/\r?\n/);

            const matchingLines = [];

            for (let i = 0; i < lines.length; i++) {
                if (
                    lines[i]
                        .toLowerCase()
                        .includes(normalizedQuery)
                ) {
                    matchingLines.push(i + 1);

                    if (
                        matchingLines.length >= 10
                    ) {
                        break;
                    }
                }
            }

            if (matchingLines.length === 0) {
                continue;
            }

            filesWithMatches++;

            for (const lineNumber of matchingLines) {
                totalMatches++;

                resultFragments.push(
                    buildResult(
                        file,
                        lineNumber,
                        lines,
                        query
                    )
                );
            }
        }

        if (searchStatus) {
            searchStatus.textContent =
                totalMatches +
                " Treffer in " +
                filesWithMatches +
                " Dateien.";
        }

        if (resultFragments.length === 0) {
            searchResults.innerHTML =
                '<div class="alert alert-secondary">' +
                "Keine Treffer." +
                "</div>";

            return;
        }

        searchResults.innerHTML =
            resultFragments.join("");
    }


    let searchTimer = null;

    searchInput.addEventListener(
        "input",
        function () {
            clearTimeout(searchTimer);

            searchTimer =
                setTimeout(
                    performSearch,
                    150
                );
        }
    );


    if (clearSearch) {
        clearSearch.addEventListener(
            "click",
            function () {
                searchInput.value = "";
                searchResults.innerHTML = "";

                if (searchStatus) {
                    searchStatus.textContent =
                        window.SEARCH_INDEX
                            ? window.SEARCH_INDEX.length +
                              " Java-Dateien geladen."
                            : "";
                }

                searchInput.focus();
            }
        );
    }

})();
"""

  write_text(
    SITE / "site.js",
    js,
  )


# ============================================================
# Version generation
# ============================================================

def generate_version(
  source_root,
  version_type,
  version_base_url,
  pr=None,
):
  """
  Generate one complete version of the project.
  """

  version_directory = (
    SITE
    / Path(version_base_url.lstrip("/"))
  )

  # For URLs such as /repo/, Path gives repo.
  # For /repo/pr/17/, it gives repo/pr/17.
  version_directory.mkdir(
    parents=True,
    exist_ok=True,
  )

  # --------------------------------------------------------
  # Search index
  # --------------------------------------------------------

  write_search_index(
    source_root,
    version_directory,
  )

  # --------------------------------------------------------
  # README / pom / source files
  # --------------------------------------------------------

  for path in source_root.rglob("*"):
    if not path.is_file():
      continue

    relative = path.relative_to(source_root)
    relative_string = normalize_path(relative)

    if is_excluded(relative_string):
      continue

    if not is_source_file(relative_string):
      continue

    output_path = (
      version_directory
      / Path(relative_string).with_suffix(".html")
    )

    page = render_source_file(
      source_root,
      relative_string,
      version_base_url,
    )

    write_text(
      output_path,
      page,
    )

  # --------------------------------------------------------
  # Project overview
  # --------------------------------------------------------

  overview = render_project_overview(
    source_root,
    version_type,
    version_base_url,
    pr=pr,
  )

  write_text(
    version_directory / "index.html",
    overview,
  )


# ============================================================
# Main generation
# ============================================================

def main():
  print("========================================")
  print("Generating GitHub Pages site")
  print("========================================")
  print(f"Repository: {REPO}")
  print(f"Repository name: {REPO_NAME}")
  print(f"Site base: {site_base()}")
  print()

  clean_site()
  copy_bootstrap()

  main_commit = get_main_commit()

  print(f"Main commit: {main_commit}")

  # --------------------------------------------------------
  # Current main
  # --------------------------------------------------------

  print()
  print("Generating main ...")

  main_source = ROOT / ".pages-main-source"

  if main_source.exists():
    shutil.rmtree(main_source)

  create_snapshot_from_commit(
    main_commit,
    main_source,
  )

  generate_version(
    source_root=main_source,
    version_type="main",
    version_base_url=version_base("main"),
  )

  # --------------------------------------------------------
  # Historical merged PRs
  # --------------------------------------------------------

  merged_prs = load_merged_prs()

  print()
  print(f"Found {len(merged_prs)} merged PR(s).")

  for pr in merged_prs:
    number = pr["number"]
    sha = pr["sha"]

    print(
      f"Generating PR #{number} "
      f"({sha[:12]}) ..."
    )

    pr_source = (
      ROOT
      / ".pages-pr-source"
      / str(number)
    )

    if pr_source.exists():
      shutil.rmtree(pr_source)

    create_snapshot_from_commit(
      sha,
      pr_source,
    )

    generate_version(
      source_root=pr_source,
      version_type="pr",
      version_base_url=version_base(
        "pr",
        number,
      ),
      pr=pr,
    )

  # --------------------------------------------------------
  # Global JavaScript
  # --------------------------------------------------------

  write_site_javascript()

  # --------------------------------------------------------
  # Safety check
  # --------------------------------------------------------

  forbidden = list(
    SITE.rglob("merged-prs.json")
  )

  if forbidden:
    raise RuntimeError(
      "ERROR: merged-prs.json would be published: "
      + ", ".join(str(p) for p in forbidden)
    )

  # Search index files are intentional.
  # merged-prs.json must never be inside _site.

  # --------------------------------------------------------
  # Cleanup temporary snapshots
  # --------------------------------------------------------

  for temporary in [
    ROOT / ".pages-main-source",
    ROOT / ".pages-pr-source",
  ]:
    if temporary.exists():
      shutil.rmtree(temporary)

  print()
  print("========================================")
  print("Pages site successfully generated.")
  print("========================================")
  print(f"Output: {SITE}")


if __name__ == "__main__":
  main()
