@startuml

class Bank {
    +sucheKonto(iban: String): Konto
    +kundeAnlegen(kunde: Kunde)
    +kontoAnlegen(konto: Konto)
    {static} +ibanErzeugen(): String
}

class Kunde {
    -nummer: UUID
    -name: String
    -wohnort: Adresse
    --
    +wohnortÄndern(adresse: Adresse)
}

class Konto {
    -iban: String
    -stand: Geldbetrag
    {stand >= 0}
    --
    +einzahlen(betrag: Geldbetrag)
    +abheben(betrag: Geldbetrag)
    +getStand(): Geldbetrag
}

class Adresse {
    -straße: String
    -hausnummer: String
    -PLZ: String
    -ort: String
}

Bank "1" --> "0..*" Kunde : kennt
Bank "1" --> "0..*" Konto : kennt
Kunde "1" <-- "0..*" Konto : besitzt
Kunde "1" *--> "1" Adresse : hat

@enduml
